version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: containerpass
      MYSQL_DATABASE: db
    volumes:
      - "./configs/mysql.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"
      - "./database/create-order-management.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - order-network
    ports:
      - "3306:3306"
  admin:    
    image: adminer    
    ports:      
      - "8080:8080"
    networks:
      - order-network
    depends_on: 
      - mysql-development
      
  order-management:
    #restart: on-failure
    depends_on: 
      - mysql-development
    image: order-management-app
    ports:
      - "8090:8090"
    networks:
      - order-network    


networks:
  order-network:
    driver: bridge