version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: containerpass
      MYSQL_DATABASE: db
    ports:
      - "3308:3306"
    volumes:
      - "./configs/mysql.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"
  admin:    
    image: adminer    
    ports:      
      - "8090:8080"
      
  order-management:
    image: order-management-app
    ports:
      - "8091:8080"