CREATE TABLE IF NOT EXISTS Order (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ReceivedDate  TIMESTAMP NOT NULL,
  TotalAmount FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS Product (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  detail VARCHAR(200) NOT NULL,
  productType VARCHAR(20) NOT NULL,
  price FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS Stock (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ProductID INT NOT NULL,
  Quantity INT NOT NULL,
  ShopNo INT NOT NULL,
  FOREIGN KEY (ProductID) REFERENCES Product(ID)
);

CREATE TABLE IF NOT EXISTS Customer (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  SURNAME VARCHAR(20) NOT NULL,
  Quantity INT NOT NULL,
  ShopNo INT NOT NULL,
  FOREIGN KEY (ProductID) REFERENCES Product(ID)
);

CREATE TABLE IF NOT EXISTS Address (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  STREET VARCHAR(20) NOT NULL,
  CITY VARCHAR(20) NOT NULL,
  COUNTRY VARCHAR(20) NOT NULL,
  STATE VARCHAR(20) NOT NULL,
  POSTAL_CODE VARCHAR(20) NOT NULL,
  STREET_NUMBER INT NOT NULL,
);