CREATE TABLE IF NOT EXISTS order_customer (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  SURNAME VARCHAR(20) NOT NULL,
  PHONE_NUMBER INT(11) NOT NULL,
  EMAIL VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS order_address (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  STREET VARCHAR(20) NOT NULL,
  CITY VARCHAR(20) NOT NULL,
  COUNTRY VARCHAR(20) NOT NULL,
  STATE VARCHAR(20) NOT NULL,
  POSTAL_CODE VARCHAR(20) NOT NULL,
  STREET_NUMBER INT NOT NULL,
  CUSTOMER_ID INT NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES order_customer(ID),
  UNIQUE KEY UNIQUE_ADRRESS (ID,CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS order_order (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  RECEIVED_DATE  TIMESTAMP NOT NULL,
  TOTAL_AMOUNT FLOAT NOT NULL,
  CUSTOMER_ID INT NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES order_customer(ID)
);

CREATE TABLE IF NOT EXISTS order_item (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  QUANTITY INT NOT NULL,
  ORDER_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES order_order(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES order_product(ID),
  UNIQUE KEY UNIQUE_ADRRESS (ORDER_ID,PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS order_product (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  DETAIL VARCHAR(200) NOT NULL,
  PRODUCT_TYPE VARCHAR(20) NOT NULL,
  PRICE FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS order_stock (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  SHOP_NO INT NOT NULL,
  FOREIGN KEY (PRODUCT_ID) REFERENCES order_product(ID),
  UNIQUE (PRODUCT_ID)
);